/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.3.3/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "aws-lambda-decrypter"
include("lib")

pluginManagement {
    val kotlinVersion: String by settings

    plugins {
        id("java")
        id("java-library")
        id("maven-publish")
        id("org.jetbrains.kotlin.jvm") version kotlinVersion
        id("com.github.johnrengelman.shadow") version "7.1.2"
        id("org.ajoberstar.grgit") version "5.0.0"
        id("org.jlleitschuh.gradle.ktlint") version "11.0.0"
    }
}

buildscript {
    val kotlinVersion: String by settings

    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    }
    repositories {
        mavenCentral()
    }
}
